# Generated by Django 6.0.2 on 2026-02-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingsession',
            name='last_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='last_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='last_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='total_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='total_time',
            field=models.FloatField(default=0),
        ),
    ]
