# Generated by Django 6.0.2 on 2026-02-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_locationpoint'),
        ('tracking', '0002_trackingsession_last_lat_trackingsession_last_lng_and_more'),
    ]

    operations = [
    ]
